version: '3'

services:

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  strapi-app:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    volumes:
      - ./volumes/strapi-app:/usr/src/api/strapi-app
    depends_on:
      - strapi-db
    restart: always
    labels:
      - "traefik.frontend.rule=Host:api.localhost"

  strapi-db:
    build: ./db
    environment:
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - ./volumes/strapi-db:/data/db
    restart: always
    labels:
      - "traefik.enable=false"

  web-app:
    build: ./app
    labels:
      - "traefik.frontend.rule=Host:web.localhost"
